language: node_js
node_js:
  - "8"
  - "10"
cache: yarn
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script:
  - yarn run lint
after_script: greenkeeper-lockfile-upload